name = "bowlsteam"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "bowlsteam-db"
database_id = "bf13788b-4706-4942-84d9-b890dc3fc4b5"

[vars]
ADMIN_KEY = "bowlsteam-admin-2026"
